name: bbb

name1: aaaa
hello: good morning
spring:
  profiles:
    active: default
---

spring:
  profile: dev
name1: 1234

---

spring:
  profile: hello
name1: bbbb

---
management:
  security:
    enabled: false
  port: 8888
  context-path: /abc
  
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: true
    
info:
  app:
    name: spring-boot-actuator
    version: 1.0.0
    
   


